# Generated by Django 4.0.5 on 2022-07-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_rename_author_id_note_note_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_id',
            new_name='user_id',
        ),
    ]
