# Generated by Django 4.0.5 on 2022-07-23 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_note_id_note_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 19, 14, 27, 403464)),
        ),
    ]
