# Generated by Django 4.0.5 on 2022-07-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_note_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
    ]
