# Generated by Django 4.0.5 on 2022-08-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_rename_user_id_note_user_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
