# Generated by Django 4.0.5 on 2022-08-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_delete_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='collaborator',
        ),
    ]
