# Generated by Django 4.0.5 on 2022-08-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_remove_note_collaborator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='user_id',
        ),
    ]
