# Generated by Django 4.0.5 on 2022-08-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='user_id',
            new_name='user',
        ),
    ]
