# Generated by Django 4.0.5 on 2022-08-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_rename_user_id_label_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='user',
            new_name='user_id',
        ),
    ]
