# Generated by Django 4.0.5 on 2022-07-25 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_logindata'),
    ]

    operations = [
        migrations.AddField(
            model_name='logindata',
            name='token',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
