# Generated by Django 4.0.5 on 2022-07-27 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_logindata_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginData',
        ),
    ]
